### ISSUE TITLE
>> print("Hello World") only prints World

### ISSUE THREAD

**Issue by pj-mathematician** [BenjaminHinchliff/discord-python-interpreter-bot#2]
`>> print("Hello World)` returns `World` only, generally speaking, `>> print("str1 str2 str3....")` prints `str2 str3 ....`

![Screenshot_20201120-201602](https://user-images.githubusercontent.com/55710610/99813736-1134c500-2b6e-11eb-8578-866724adb3f7.png)

**Comment by BenjaminHinchliff** [comment]
Thanks for the bug report! However, I'm having trouble replicating the issue on my testing server - to use your example:
![image](https://user-images.githubusercontent.com/46175830/99862405-77a9eb00-2b4e-11eb-9d2f-1b94bddc96cd.png)

I don't really know what could be causing the issue, but I'll take a quick poke around my code and see if I can find anything that might be causing this, and I also plan to check the open issues for RestrictedPython to see if that could be a problem.

In the meantime, could I have a little more information about your OS and Discord version (just in case)? Oh, and out of curiosity, is there some reason our code boxes look different?

**Comment by BenjaminHinchliff** [comment]
I made a few little improvements - improved a nasty regex that *might* have been mangling your input, and updated the dependencies. Let me know if this is still an issue.

**Comment by pj-mathematician** [comment]
Thank you for your response, I realised i was using the Android Alpha version v49.1 at that time, i tested it on the stable android version(v47.x) and on the desktop version, and it worked pretty well. 

Interestingly, the test case I used previously is showing the desired result on the stable versions
![Screenshot_20201121-095724](https://user-images.githubusercontent.com/55710610/99867492-fdc24200-2bdf-11eb-8b14-02b177e84879.png)

**Comment by BenjaminHinchliff** [comment]
Well, I guess I'll close this for now, since I don't think it's a problem with my code. I'll stay vigilant and try to fix it if it continues. Just let me know if you have any more problems.
