### ISSUE TITLE
Runtime error: name 'all' is not defined

### ISSUE THREAD

**Issue by TheRealFanjin** [BenjaminHinchliff/discord-python-interpreter-bot#3]
It doesn't work when I use `all()`

**Comment by BenjaminHinchliff** [comment]
This is actually intended behavior - as of now it is set to have a *[very](https://github.com/zopefoundation/RestrictedPython/blob/master/src/RestrictedPython/Guards.py#L30)* restricted set of globals. This doesn't include the `all` function. I'll look into opening up the globals a bit, but I obviously have to be careful to avoid people breaking out of the execution environment.

**Comment by TheRealFanjin** [comment]
Ok, thanks

**Comment by BenjaminHinchliff** [comment]
I've changed the configuration settings to allow usage of the `any` and `all` functions, along with some other utilities. It'll take a few minutes to propagate to the server, but it should work soon. Let me know if you have any further issues.
